///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Demo2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Demo2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b85d1140-b3d3-43ac-9b18-241879c69ee0")]
    public partial class Demo2Repository : RepoGenBaseFolder
    {
        static Demo2Repository instance = new Demo2Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Demo2Repository element repository.
        /// </summary>
        [RepositoryFolder("b85d1140-b3d3-43ac-9b18-241879c69ee0")]
        public static Demo2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Demo2Repository() 
            : base("Demo2Repository", "/", null, 0, false, "b85d1140-b3d3-43ac-9b18-241879c69ee0", ".\\RepositoryImages\\Demo2Repositoryb85d1140.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b85d1140-b3d3-43ac-9b18-241879c69ee0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Demo2RepositoryFolders
    {
    }
#pragma warning restore 0436
}
